# Title
page_title                                : SmartPack Projects

fdroid_link                               : 
playstore_link                            : 
app_icon                                  : assets/siteicon.png
app_name                                  : SmartPack Projects
app_price                                 : Free
app_description                           : Welcome to the home page of SmartPack projects, a group of open-source and privacy-friendly applications designed to improve the overall android user experience.

enable_smart_app_banner                   : true

# Features
features                                  :

  - title                                 : Simple
    description                           : All the apps are essentially simple and easy to use
    fontawesome_icon_name                 : magic

  - title                                 : Open-Source
    description                           : Up-to-date source code, which is always open for suggestions or/and contributions
    fontawesome_icon_name                 : code-branch

  - title                                 : Privacy-friendly
    description                           : We respect your privacy (no data collection, storing, or sharing)
    fontawesome_icon_name                 : user-secret

  - title                                 : Multilingual
    description                           : Thanks to the community contributions, most of these apps are available in many languages
    fontawesome_icon_name                 : globe

  - title                                 : Free
    description                           : All these apps are free (or atleast, a free version always available at F-Droid/GitHub)
    fontawesome_icon_name                 : eye-dropper


# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/pic001.png
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : blue

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"


####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown

# Brave verification
include: [".well-known"]
